### ISSUE TITLE
TypeError: Sheet.insert_row() got an unexpected keyword argument 'values'

### ISSUE THREAD

**Issue by akashj87** [VarunS2002/Python-NSE-Option-Chain-Analyzer#67] opened 2024-06-13 05:49 UTC
after doing tksheet version 6.3.5, following error is resolved but new errror is appearing

[2024-06-13 11:11:11 - INFO ] ----------Logging Started----------
[2024-06-13 11:11:11 - INFO ] Windows 10 .py version 5.5
[2024-06-13 11:11:29 - ERROR] 
[2024-06-13 11:11:29 - ERROR] Warning (from warnings module):
[2024-06-13 11:11:29 - ERROR]   File "C:\Users\akash\Documents\Python-NSE-Option-Chain-Analyzer-5.5\NSE_Option_Chain_Analyzer.py", line 1454
[2024-06-13 11:11:29 - ERROR]     int_put_oi_2: int = int(entire_oc.iloc[i, [20]][0])
[2024-06-13 11:11:29 - ERROR] FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
[2024-06-13 11:11:29 - ERROR] Exception in Tkinter callback
[2024-06-13 11:11:29 - ERROR] Traceback (most recent call last):
  File "C:\Python\Lib\tkinter\__init__.py", line 1967, in __call__
[2024-06-13 11:11:29 - ERROR]     return self.func(*args)
[2024-06-13 11:11:29 - ERROR]            ^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\tkinter\__init__.py", line 861, in callit
[2024-06-13 11:11:29 - ERROR]     func(*args)
  File "C:\Users\akash\Documents\Python-NSE-Option-Chain-Analyzer-5.5\NSE_Option_Chain_Analyzer.py", line 1536, in main
[2024-06-13 11:11:29 - ERROR]     self.set_values()
  File "C:\Users\akash\Documents\Python-NSE-Option-Chain-Analyzer-5.5\NSE_Option_Chain_Analyzer.py", line 1282, in set_values
[2024-06-13 11:11:29 - ERROR]     self.sheet.insert_row(values=output_values, add_columns=True)
TypeError: Sheet.insert_row() got an unexpected keyword argument 'values'

===========================================================

line 1409
[2024-06-13 11:27:28 - ERROR]     int_call_oi: int = int(entire_oc.iloc[i, [0]][0])
[2024-06-13 11:27:28 - ERROR] FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
[2024-06-13 11:27:28 - ERROR] 
[2024-06-13 11:27:28 - ERROR] Warning (from warnings module):
[2024-06-13 11:27:28 - ERROR]   File "C:\Users\akash\Documents\Python-NSE-Option-Chain-Analyzer-5.5\NSE_Option_Chain_Analyzer.py", line 1417
[2024-06-13 11:27:28 - ERROR]     int_put_oi: int = int(entire_oc.iloc[i, [20]][0])
[2024-06-13 11:27:28 - ERROR] FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
[2024-06-13 11:27:28 - ERROR] 
[2024-06-13 11:27:28 - ERROR] Warning (from warnings module):
[2024-06-13 11:27:28 - ERROR]   File "C:\Users\akash\Documents\Python-NSE-Option-Chain-Analyzer-5.5\NSE_Option_Chain_Analyzer.py", line 1446
[2024-06-13 11:27:28 - ERROR]     int_call_oi_2: int = int(entire_oc.iloc[i, [0]][0])
[2024-06-13 11:27:28 - ERROR] FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
[2024-06-13 11:27:28 - ERROR] 
[2024-06-13 11:27:28 - ERROR] Warning (from warnings module):
[2024-06-13 11:27:28 - ERROR]   File "C:\Users\akash\Documents\Python-NSE-Option-Chain-Analyzer-5.5\NSE_Option_Chain_Analyzer.py", line 1454
[2024-06-13 11:27:28 - ERROR]     int_put_oi_2: int = int(entire_oc.iloc[i, [20]][0])
[2024-06-13 11:27:28 - ERROR] FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

**Comment by VarunS2002** [comment] 2024-06-14 06:51
Duplicate of #64 
Workaround is to revert `tksheet` version to  `6.3.5`

**Closed as completed by VarunS2002** 2024-06-14 06:51 UTC
Labels: duplicate

**Comment by VarunS2002** [comment] 2024-10-16 12:41
Fixed in the [latest version](https://github.com/VarunS2002/Python-NSE-Option-Chain-Analyzer/releases/5.6).
