### ISSUE TITLE
error while run this code

### ISSUE THREAD

**Issue by parkashgoel** [VarunS2002/Python-NSE-Option-Chain-Analyzer#73] opened 2024-10-27 06:42 UTC
![error](https://github.com/user-attachments/assets/fc78886d-108c-458d-95fd-77e636dac4c5)

**Comment by parkashgoel** [comment] 2024-10-27 06:44
![image](https://github.com/user-attachments/assets/913e0d24-aca0-4e3c-8b8a-3389f800ee3b)

**Comment by VarunS2002** [comment] 2024-10-27 12:22
Duplicate of #71

**Closed as completed by VarunS2002** 2024-10-27 12:22 UTC
Labels: duplicate
