### ISSUE TITLE
Getting error 

### ISSUE THREAD

**Issue by amit-lalakiya** [VarunS2002/Python-NSE-Option-Chain-Analyzer#33] opened 2022-02-28 06:43 UTC
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\amit\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\Users\amit\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 814, in callit
    func(*args)
  File "D:\Market\Python\ExcelTrading\OC_Analyzer_VarunS2002.py", line 1571, in main
    self.set_values()
  File "D:\Market\Python\ExcelTrading\OC_Analyzer_VarunS2002.py", line 1397, in set_values
    self.sheet.see(last_row)
  File "C:\Users\amit\venv\python39\lib\site-packages\tksheet\_tksheet.py", line 1137, in see
    self.MT.see(row, column, keep_yscroll, keep_xscroll, bottom_right_corner, check_cell_visibility = check_cell_visibility, redraw = redraw)
  File "C:\Users\amit\venv\python39\lib\site-packages\tksheet\_tksheet_main_table.py", line 1050, in see
    yvis, xvis = self.cell_is_completely_visible(r = r, c = c, separate_axes = True)
  File "C:\Users\amit\venv\python39\lib\site-packages\tksheet\_tksheet_main_table.py", line 1106, in cell_is_completely_visible
    x1, y1, x2, y2 = self.GetCellCoords(r = r, c = c, sel = True)
  File "C:\Users\amit\venv\python39\lib\site-packages\tksheet\_tksheet_main_table.py", line 2509, in GetCellCoords
    return self.col_positions[c] + 1,self.row_positions[r] + 1, self.col_positions[c + 1], self.row_positions[r + 1]
IndexError: list index out of range

**Comment by VarunS2002** [comment] 2022-02-28 08:10
Most likely a duplicate of #25.
Re-open issue if not.

**Closed by VarunS2002** 2022-02-28 08:10 UTC

**Comment by amit-lalakiya** [comment] 2022-02-28 11:52
Your suggested fix worked. Now it is working as intended.  I should have looked for the error reports before raising a new one. Thanks for making such an amazing tool.

**Comment by VarunS2002** [comment] 2022-03-01 05:44
@amit-lalakiya No issues. Thanks!
