### ISSUE TITLE
requests.exceptions.JSONDecodeError

### ISSUE THREAD

**Issue by chettyrajesh** [VarunS2002/Python-NSE-Option-Chain-Analyzer#69] opened 2024-10-15 13:25 UTC
Error: Expecting value: line 1 column 1 (char 0) <class 'requests.exceptions.JSONDecodeError'> 20

GUI Error message
![Screenshot 2024-10-15 185311](https://github.com/user-attachments/assets/a1b85450-cab8-43b7-9585-25288950cf81)

JSON content is showing with encrypted text.
![Screenshot 2024-10-15 185457](https://github.com/user-attachments/assets/ace3f935-7a45-40f8-bee7-b25b649fca9a)

**Comment by VarunS2002** [comment] 2024-10-16 12:43
Duplicate of #65.
Fixed in the [latest version](https://github.com/VarunS2002/Python-NSE-Option-Chain-Analyzer/releases/5.6).

**Comment by VarunS2002** [comment] 2024-10-16 12:43
Thanks for including the JSON content!

**Closed as completed by VarunS2002** 2024-10-16 12:43 UTC
Labels: duplicate

**Comment by chettyrajesh** [comment] 2024-10-17 08:49
Thank you
