### ISSUE TITLE
Bank Nifty spot price shows zero

### ISSUE THREAD

**Issue by sudhirdhongade** [VarunS2002/Python-NSE-Option-Chain-Analyzer#6] opened 2021-01-12 07:49 UTC
Hi Varun,

I actually have 3 concerns - 

1. The 'Value' column shows 0 for Bank nifty. Tried various strike prices but result is same.
2. There is a delay of about 1 min for new updated values to appear.
3. A minute update is skipped sometimes. For eg: If the last update was on 13:06:27 then the next update may come at 13:08:57.

Also would really appreciate if you could mention few signals that one can use as a indication to take a trade. For eg: Put Sum becomes more than Call Sum which indicates price may go Up.

![OCA](https://user-images.githubusercontent.com/52794179/104284827-b158fb80-54d8-11eb-80ec-733987cc0997.JPG)

Keep up the good work and Thank you in advance!

**Comment by VarunS2002** [comment] 2021-01-12 11:05
Addressing your concerns:
1. I found out the issue is that NSE's data is broken sometimes for certain strike prices. I've thought of a workaround and will fix it soon.
2 and 3. The NSE website doesn't update at fixed intervals. Sometimes <1 min and sometimes up to 5 minutes. So when it updates the program shows the data with the time at which the site updated.

Also, are you using the .py version or the .exe version?

**Comment by sudhirdhongade** [comment] 2021-01-12 17:21
I am using the .exe version. Actually I am just getting started with Python. That's how I ended up on this page.

Thank you for your prompt response. Much appreciated..!

**Comment by VarunS2002** [comment] 2021-01-13 02:28
The Open Interest label turning bullish or bearish is the indication you're looking for. In the next update you can enable notifications for when it changes.

**Comment by VarunS2002** [comment] 2021-01-15 07:38
Fixed in the Latest release [4.0](https://github.com/VarunS2002/Python-NSE-Option-Chain-Analyzer/releases/tag/4.0)

**Closed by VarunS2002** 2021-01-15 07:38 UTC
Labels: bug, enhancement
