### ISSUE TITLE
login issue 

### ISSUE THREAD

**Issue by kanthusb** [VarunS2002/Python-NSE-Option-Chain-Analyzer#70] opened 2024-10-16 07:37 UTC
while trying to login its showing error
![image](https://github.com/user-attachments/assets/ca3bd315-a7dc-47a7-b9b9-826ce602b57e)

**Comment by VarunS2002** [comment] 2024-10-16 12:42
Duplicate of #65.
Fixed in the [latest version](https://github.com/VarunS2002/Python-NSE-Option-Chain-Analyzer/releases/5.6).

**Closed as completed by VarunS2002** 2024-10-16 12:42 UTC
Labels: duplicate
